language: node_js
node_js: stable
  
sudo: required
before_install:
#  - npm install -g node-gyp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
# S: Build Lifecycle
install:
  - npm install
  - npm config set python `which python`
  - npm install -S hexo-generator-json-content
  - npm install hexo-ruby-character --save
#before_script:
  - npm install -g gulp

script:
  - hexo generate
  - gulp
after_script:
  - mkdir ./public/post_images
  - mv -f ./source/_posts/images/* ./public/images/ 
  - cd ./public
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${EMAIL}"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - src
