language: node_js
node_js: #stable
  - "7.1.0"
sudo: required
before_install:
#  - npm install nodejieba
addons:
  apt:
    packages:
    - gcc-4.8
    - g++-4.8
install:
  - npm install --production
#  - npm install -S hexo-generator-json-content
before_script:
  - npm install -g gulp

script:
  - hexo generate
  - gulp
after_script:
  - mkdir ./public/post_images
  - mv -f ./source/_posts/images/* ./public/images/ 
  - cd ./public
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${EMAIL}"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - src
