language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
  - npm install -S hexo-generator-json-content
  - npm install -S hexo-renderer-markdown-it


#before_script:
  - npm install -g gulp

script:
  - hexo generate
  - gulp
after_script:
  - mkdir ./public/post_images
  - mv -f ./source/_posts/images/* ./public/post_images/ 
  - cd ./public
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${EMAIL}"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - src
