# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 侯杰的博客
subtitle:
description: 坚持把简单的事情做好就是不简单，坚持把平凡的事情做好就是不平凡。所谓成功，就是在平凡中做出不平凡的坚持。
author: 侯杰
author_title: '图书馆里的学习生涯'
avatar: css/images/avatar.jpg
location: 'Shanxi, China'
follow: https://github.com/deffyc
email: # Your email (Used to show Gravatar).
language: zh-CN
timezone:
since: 2012 # The start year showing in your copyright section.

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.ccsyue.com/
root: /
permalink: :year/:title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 7
pagination_dir: page

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: icarus

# Disqus
# disqus_shortname: hexo-theme-icarus

# DuoShuo
# duoshuo_shortname: hexo-theme-icarus

# Swiftype
#swiftype_install_key: fKCWzKJSMacajfY-DTha

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type:git
  repo:git@github.com:deffyc/deffyc.github.io.git
  branch:master
  message:hexo

# Prose
prose:
  rooturl: 'source'
  siteurl: 'https://blog.ccsyue.com/'
#  relativeLinks: 'http://meetcircle.co/links.jsonp'
  media: 'source/_post/images'
  ignore:
    - .gitignore
    - _config.yml
  metadata:
  	'content/_post'
      - name: "title"
        field:
          element: "text"
          type: "text"
          value: "text"
          label: "title"
      - name: "date"
        field:
          element: "text"
          type: "datetime"
          label: "category"
          value: CURRENT_DATETIME
          placeholder: "YYYY-MM-DD HH:MM"
      - name: "tags"
        field:
          element: "multiselect"
          type: "multiselect"
          label: "tags"
          value: "中共党员,鑫鑫,英语流利说"
          alterable: true
      - name: "category"
        field:
          element: "text"
          type: "text"
          label: "category"
          value: "未分类"
