# Menus
menu:
#  首页: .
  归档: archives/
  分类: categories/
  标签: tags/
  关于: about/
  写作: 'https://prose.ccsyue.com/#deffyc/blog/new/src/source/_posts'

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: images/avatar.jpg
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: 天边
        author_title: study & work
        location: ShanXi, China
        follow: https://github.com/deffyc
    highlight: monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: favicon.ico
    social_links:
        #github: https://github.com/deffyc
        #rss: 
    social_link_tooltip: true # enable the social link tooltip, options: true, false

#CDN
cdn: //blogstatic.ccsyue.com/

# Widgets
widgets:
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: false # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo: #freeinhere # enter duoshuo shortname here
    youyan: # enter youyan uid here
    gentie:  # enter wangyi gentie productkey here
    gitment:
        owner: deffyc
        repo: blog
        client_id: dd6b1da7626b499e8c4f
        client_secret: 003484dba62676643e357e4676220f772e9ce84e

# Share
#share: bdshare #default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justified-gallery: true # options: true, false
    google_analytics:  # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: f2f9969340678b8cb168216346d7b7d8 # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        导航: https://e.ccsyue.com/
